### PR TITLE
use user/pass flags

### LINKED ISSUE #253: docker:// transport requires "docker login" and doesn't obey --username and --password
If you try to do a `skopeo copy` to a Docker registry repository that doesn't exist you get an error:

```
% skopeo copy docker://opensuse docker://cyphar/nonexistant
Getting image source signatures
Copying blob sha256:467db25190688bc9dc1d5fd6dbced1ac56f55d93a942987f448e62ad2614e46e
 0 B / 46.97 MB [--------------------------------------------------------------]
FATA[0004] Error writing blob: not authorized to read from destination repository cyphar/nonexistent
```

The above example does work if you first do a `docker push cyphar/nonexistent` but that's quite annoying. I'm not sure if this should be transparently handled by containers/image or if we should be implementing this policy.

### PR DESCRIPTION
**Pull request by runcom**
We already use global flags for docker specific stuff. This patch enables `--username` and `--password` to be passed down to `containers/image` to setup docker's registries auth.

Fixes #253 

@mtrmac @cyphar PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by mtrmac** [comment]
I am not really thrilled with the generic option names: if `--username` and `--password` never worked, nothing stops us from naming them `--docker-username` / `--docker-password`. 

I am worried that w really shouldn’t send the same password to several different servers. OTOH the distinction really isn’t between transport types, but between individual hostnames, and that would be a horrible UI, so a generic `--username` and fervently hoping that the users know what they are doing might be the best I can do.

This should also restore `TestCanAuthToPrivateRegistryV2WithoutDockerCfg` and perhaps some of the neighboring tests, though.

After that, I guess, LGTM.

**Comment by mtrmac** [comment]
(As for “we already do use generic option names for Docker-specific options”, that's partly legacy. And partly using `--cert-path` for an unwanted service is not a vulnerability, but sending a password to an unwanted service is. But, really, I am bad at designing UIs,)

**Comment by runcom** [comment]
> This should also restore TestCanAuthToPrivateRegistryV2WithoutDockerCfg and perhaps some of the neighboring tests, though

Sort of.. I have to mock an empty Docker cfg first. I'll add that though, thx. 

> I am not really thrilled with the generic option names: if --username and --password never worked, nothing stops us from naming them --docker-username / --docker-password.

We used to have user/pass flag in the very first skopeo versions :/

**Comment by mtrmac** [comment]
Yeah; I am not _thrilled_ with `--password` but I can live with that.

**Comment by runcom** [comment]
@mtrmac what if we add `--src-username` and `--src-password` and the same for `dest`. That's not horrible to me and IIUC should solve your concern around wrongly sending a password to a wrong server.

**Comment by mtrmac** [comment]
That’s great idea. We can very confidently expect that the sets of servers underlying a transport(`atomic:` native API + Docker registry API, `docker:` native API + sigstore) must be under a shared control.

Yes to `--{src,dest}-{username,password}`, please.

**Comment by runcom** [comment]
Alright, do note that I'll make these new flags available only to `copy`. `inspect` and the now deprecated `layers` command will continue to behave as usual (w/o any user/pass flag set).

**Comment by runcom** [comment]
Or wait, I can add username and password flag locally for inspect/layers commands. I'll do this way.

**Comment by runcom** [comment]
@mtrmac PTAL, before going ahead and add docs/tests/`containers/image` bits, I would like to have your ack on the direction with `copy`. I'll also fix `layers|inspect` once we agree on `copy`.

**Comment by rhatdan** [comment]
I don't like options with dashes ("-") in them.  Could we look at other tools like ssh? Would
```
--src dwalsh/password@registry --dest mitr/foobar@remote
```
be better?

**Comment by runcom** [comment]
@rhatdan fine, but `--src` isn't clear enough because it's not saying we're talking about credentials

**Comment by runcom** [comment]
We don't need to specify the registry also, that's implied by src and dest in the command and we don't need that (something like that is how the Docker auth config file works but that's another story, here in the cli we directly honor user/pass combination without checking the registry they'll be used to authenticate against)

**Comment by runcom** [comment]
@rhatdan @mtrmac BTW, I'm fine compacting "username:password" in the cli as it  doesn't make sense to have 2 flags for user/pass when you must always use both. I'll rework this PR once we agree on flags naming though.

**Comment by rhatdan** [comment]
@runcom It would help me if you gave a couple of examples of what you are proposing for a CLI.

**Comment by runcom** [comment]
Like `--src-creds runcom:password` - modulo no dash in the flag

**Comment by rhatdan** [comment]
I like that better

**Comment by mtrmac** [comment]
> BTW, I'm fine compacting "username:password" in the cli as it doesn't make sense to have 2 flags for user/pass when you must always use both. I'll rework this PR once we agree on flags naming though.

That feels a bit off, as a general security habit I like to avoid formatting/parsing and in-band signalling. More importantly, it _may_ make sense to provide an username but not a password (e.g. when authenticating using a Kerberos ticket, or a smartcard)

**Comment by runcom** [comment]
> BTW, I'm fine compacting "username:password" in the cli as it doesn't make sense to have 2 flags for user/pass when you must always use both. I'll rework this PR once we agree on flags naming though.
> That feels a bit off, as a general security habit I like to avoid formatting/parsing and in-band signalling. More importantly, it may make sense to provide an username but not a password (e.g. when authenticating using a Kerberos ticket, or a smartcard)

alright, no parsing then, any idea regarding Dan's issue on naming?

**Comment by rhatdan** [comment]
Why wouldn't --cred dwalsh
Cause the passwd checks to happen to use kerberos like sshd does?

I guess if you had a case where there was a password without a user then we have a problem.

**Comment by mtrmac** [comment]
> Why wouldn't --cred dwalsh
Cause the passwd checks to happen to use kerberos like sshd does?

Good point, that works fine.

**Comment by runcom** [comment]
> Why wouldn't --cred dwalsh
> Cause the passwd checks to happen to use kerberos like sshd does?
> Good point, that works fine.

I probably missed something, are we ok with `--creds username:password`? I didn't understand Dan's example :confused:

**Comment by mtrmac** [comment]
> I don't like options with dashes ("-") in them. 

This could also be handled by providing aliases:
```go
cli.StringFlag {
    Name: "src-username, suser"
    // …
}
```

and then
```
skopeo copy --suser mitr --spass sourcepass $source --duser Miloslav --dpass destpass $dest
```
(or even `--su`/`--sp`/`--du`/`--dp` but that’s probably too unreadable).

OTOH it _is_ more typing than
```
skopeo copy --screds mitr:sourcepass $source --dcreds Miloslav:destpass $dest
```

**Comment by rhatdan** [comment]
runcom I am just giving a username not a password
--creds dwalsh 
Means Username = dwalsh No password
--creds dwalsh:foobar
Means Username=dwalsh Password=foobar.

File: cmd/skopeo/copy.go [hunk 1]
```diff
@@ -32,10 +32,14 @@ func copyHandler(context *cli.Context) error {
...
 
-	return copy.Image(contextFromGlobalOptions(context), policyContext, destRef, srcRef, &copy.Options{
+	sourceCtx, destinationCtx := contextsFromGlobalOptions(context)
+
+	return copy.Image(policyContext, destRef, srcRef, &copy.Options{
 		RemoveSignatures: removeSignatures,
 		SignBy:           signBy,
 		ReportWriter:     os.Stdout,
+		SourceCtx:        sourceCtx,
+		DestinationCtx:   destinationCtx,
```
Comment (mtrmac) [inline cmd/skopeo/copy.go]: I guess this is unavoidable :/

**Comment by mtrmac** [comment]
Overall, I like the separation of username/password but it does mean quite a bit of extra typing.

WRT the too-long-option names, we can provide shortcuts but it would still be nice to at least allow using long readable ones (`--dcreds` is also pretty cryptic).

= overall I don’t have a strong opinion on the single/two-argument decision.

**Comment by mtrmac** [comment]
> We can very confidently expect that the sets of servers underlying a transport(`atomic:` native API + Docker registry API, `docker:` native API + sigstore) must be under a shared control.

Sadly, we can’t, when uploading to `docker.io` for docker/distribution vs. company-specific sigstore.

Ouch.

(This does not _immediately_ affect this PR because that is only setting a docker/distribution username:password. But any more such cases, and telling the user to run `docker login` so that we have a hostname-associated configuration stored and not a bazillion of command-line options will start to look pretty good.)

**Comment by runcom** [comment]
> runcom I am just giving a username not a password
> --creds dwalsh
> Means Username = dwalsh No password
> --creds dwalsh:foobar
> Means Username=dwalsh Password=foobar.

Yup, thanks @rhatdan - I was asking if @mtrmac is fine with that also, Miloslav are you?

**Comment by mtrmac** [comment]
I don’t have a strong opinion on `creds` vs. `username`+`password`; separating the source and destination still seems worthwhile to me.

**Comment by runcom** [comment]
@mtrmac I was talking just about the "user:pass" format which should be parsed

**Comment by mtrmac** [comment]
> @mtrmac I was talking just about the "user:pass" format which should be parsed

Yeah, I don’t have a strong opinion. If you like that, go for it.

**Comment by runcom** [comment]
@mtrmac @rhatdan PTAL again, before going ahead and add docs/tests/`containers/image` bits, I would like to have your ack about `copy`. I'll also fix `layers|inspect` once we agree on `copy`.
The patch right now allows:
```bash
$ skopeo copy --src-creds dwalsh:password --dest-creds runcom docker://busybox docker://runcom/credentials
```

File: cmd/skopeo/utils.go [hunk 2]
```diff
@@ -1,22 +1,55 @@
...
+	}
+	return up[0], up[1], nil
+}
+
+func getDockerAuth(creds string) (*types.DockerAuthConfig, error) {
+	username, password, err := parseCreds(creds)
+	if err != nil {
+		return nil, err
+	}
+	fmt.Println(username)
```
Comment (rhatdan) [inline cmd/skopeo/utils.go]: Looks like debug outpuy

Comment (runcom) [inline cmd/skopeo/utils.go]: Yup I'll drop this

**Comment by rhatdan** [comment]
Missing changes to man pages and bash completions.

**Comment by runcom** [comment]
Yup, if @mtrmac ack on the changes done so far, I'll update man, docs and everything else (adding tests also)

**Comment by runcom** [comment]
This is ready to be reviewed fully. @mtrmac @rhatdan added man changes, README changes, tests, completions (it's auto-generated so...). What's missing is to create a PR for `containers/image` changes, I'll do that shortly after this has been reviewed.

File: README.md [hunk 3]
```diff
@@ -65,14 +66,10 @@ $ skopeo delete docker://localhost:5000/imagename:latest
 
 Private registries with authentication
 -
-When interacting with private registries, `skopeo` first looks for the Docker's cli config file (usually located at `$HOME/.docker/config.json`) to get the credentials needed to authenticate. When the file isn't available it falls back looking for `--username` and `--password` flags. The ultimate fallback, as Docker does, is to provide an empty authentication when interacting with those registries.
+When interacting with private registries, `skopeo` first looks for the Docker's cli config file (usually located at `$HOME/.docker/config.json`) to get the credentials needed to authenticate. When the file isn't available it falls back looking for `--creds` (for `skopeo inspect`) or `--src-creds|--dest-creds` (for `skopeo copy`) flags. The ultimate fallback, as Docker does, is to provide an empty authentication when interacting with those registries.
```
Comment (rhatdan) [inline README.md]: I think this is wrong.  If the user specified --creds, --src-creds, --dest-creds, it should override content in config.json rather then fall back.

File: docs/skopeo.1.md [hunk 4]
```diff
@@ -70,6 +66,10 @@ Uses the system's trust policy to validate images, rejects images not trusted by
 
   **--sign-by=**_key-id_ add a signature using that key ID for an image name corresponding to _destination-image_
 
+  **--src-creds** _username:password_ for accessing the source registry
```
Comment (rhatdan) [inline docs/skopeo.1.md]: Should this be 
```
_username[:password]_
```

**Comment by rhatdan** [comment]
Still missing bash completion fixes.

**Comment by runcom** [comment]
> Still missing bash completion fixes.

where is bash completion? `hack/make/bash_autocomplete` auto generates the bash completion on `make install` - not sure what I should fix :confused:

File: README.md (hunk 3 above)
Comment (runcom) [inline README.md]: > I think this is wrong. If the user specified --creds, --src-creds, --dest-creds, it should override content in config.json rather then fall back.

Yeah, it's already this way, this piece of the README is wrong, I'll fix it.

File: docs/skopeo.1.md (hunk 4 above)
Comment (runcom) [inline docs/skopeo.1.md]: very likely, I'll fix it

**Comment by rhatdan** [comment]
Looks like it only generates one level of bash completions.  Lets ignore this for now and we can open an issue to have a much more complete bach completions.

File: README.md [hunk 5]
```diff
@@ -88,16 +85,22 @@ $ skopeo inspect docker://myregistrydomain.com:5000/busybox
...
+$ cat /home/runcom/.docker/config.json
+{}
+
+$ skopeo inspect docker://myregistrydomain.com:5000/busybox
+FATA[0000] unauthorized: authentication required
 
-# passing --username and --password - we can see that everything goes fine
-$ skopeo --docker-cfg="" --username=testuser --password=testpassword inspect docker://myregistrydomain.com:5000/busybox
+# passing --creds - we can see that everything goes fine
+$ skopeo --docker-cfg="" --creds=testuser:testpassword inspect docker://myregistrydomain.com:5000/busybox
```
Comment (mtrmac) [inline README.md]: `--docker-cfg` seems not to exist at all

**Comment by runcom** [comment]
> Looks like it only generates one level of bash completions. Lets ignore this for now and we can open an issue to have a much more complete bach completions.

ack, there's already an issue upstream which tracks this https://github.com/urfave/cli/issues/188

File: cmd/skopeo/delete.go [hunk 6]
```diff
@@ -18,7 +18,14 @@ func deleteHandler(context *cli.Context) error {
 		return fmt.Errorf("Invalid source name %s: %v", context.Args()[0], err)
 	}
 
-	if err := ref.DeleteImage(contextFromGlobalOptions(context)); err != nil {
+	ctx := contextFromGlobalOptions(context)
+	if context.IsSet("creds") {
+		ctx.DockerAuthConfig, err = getDockerAuth(context.String("creds"))
```
Comment (mtrmac) [inline cmd/skopeo/delete.go]: If everyone is going to use it like this, shouldn't it be folded into `contextFromGlobalOptions(context, creds-option-name)`?

File: cmd/skopeo/copy.go [hunk 7]
```diff
@@ -54,5 +84,15 @@ var copyCmd = cli.Command{
 			Name:  "sign-by",
 			Usage: "Sign the image using a GPG key with the specified `FINGERPRINT`",
 		},
+		cli.StringFlag{
+			Name:  "src-creds, screds",
+			Value: "",
+			Usage: "Use `USERNAME:PASSWORD` for accessing the source registry",
```
Comment (mtrmac) [inline cmd/skopeo/copy.go]: Could this use `USERNAME[:PASSWORD]`, i.e. does that work with the template-variable markers? (If so, please fix everywhere)

File: cmd/skopeo/utils.go [hunk 8]
```diff
@@ -1,30 +1,67 @@
...
 		DockerCertPath:              c.GlobalString("cert-path"),
-		DockerInsecureSkipTLSVerify: !tlsVerify,
+		DockerInsecureSkipTLSVerify: !c.GlobalBoolT("tls-verify"),
 	}
 }
 
-// ParseImage converts image URL-like string to an initialized handler for that image.
+// parseImage converts image URL-like string to an initialized handler for that image.
 // The caller must call .Close() on the returned Image.
 func parseImage(c *cli.Context) (types.Image, error) {
```
Comment (mtrmac) [inline cmd/skopeo/utils.go]: Should `parseImageSource` be also updated to support `--creds`? (This would make it work for `skopeo layers`, though I am more concerned about the API symmetry than `layers` as such)

**Comment by runcom** [comment]
@mtrmac @rhatdan updated

File: cmd/skopeo/utils.go [hunk 9]
```diff
@@ -1,30 +1,72 @@
...
 	"github.com/containers/image/transports"
 	"github.com/containers/image/types"
 	"github.com/urfave/cli"
 )
 
-// contextFromGlobalOptions returns a types.SystemContext depending on c.
-func contextFromGlobalOptions(c *cli.Context) *types.SystemContext {
-	tlsVerify := c.GlobalBoolT("tls-verify")
+func contextFromGlobalOptions(c *cli.Context, credsFlag string) (*types.SystemContext, error) {
+	ctx := newBaseSystemContext(c)
```
Comment (mtrmac) [inline cmd/skopeo/utils.go]: I don’t think we need the separate `newBaseSystemContext` function now that `credsFlag` is handled inline.  (Eventually we may support `credsFlag == ""` to turn that off, but we don’t need that now.)

This does work just fine, feel free to merge as is.

**Comment by rhatdan** [comment]
Bash Completions https://github.com/projectatomic/skopeo/pull/256

File: cmd/skopeo/utils.go (hunk 9 above)
Comment (runcom) [inline cmd/skopeo/utils.go]: done, thx

**Comment by runcom** [comment]
> Bash Completions #256

thanks Dan, we'll merge this one and re-iterate on #256

**Comment by runcom** [comment]
my bad, I have to fix containers/image and revendor here. I'll do it asap, sorry
